### ISSUE TITLE
Sort books in series by book number on admin form

### ISSUE THREAD

**Issue by doughsay** [doughsay/ambry#25]
Instead of by inserted_at

**Comment by barrotbake** [comment]
Hey @doughsay could I work on this issue?

**Comment by doughsay** [comment]
> Hey @doughsay could I work on this issue?

@barrotbake of course! Thanks for your interest 😁

**Comment by doughsay** [comment]
@barrotbake I've added some basic instructions to the README: https://github.com/doughsay/ambry#local-development

Let me know if you have any questions on how to get started on this.
